fix(Android): 参照ライブラリ数が多くてビルド失敗する不具合を修正
https://qiita.com/hayashi-ay/items/a7a06b6f1fb0a8a25dcf をみて解決

以下エラーが発生。firebase_auth などのパッケージ追加後に
Android のビルド確認してなかったと思われる。

```
BUILD FAILED in 4s
[!] App requires Multidex support
    Multidex support is required for your android app to build since the number of methods has exceeded 64k. See https://docs.flutter.dev/deployment/android#enabling-multidex-support for more information. You may pass the --no-multidex flag to skip Flutter's multidex support to use a manual solution.
    Flutter tool can add multidex support. The following file will be added by flutter:
        android/app/src/main/java/io/flutter/app/FlutterMultiDexApplication.java
cannot prompt without a terminal ui
Exception: Gradle task assembleDebug failed with exit code 1
Exited
```